import Head from "next/head";
// import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import CreateNFT from "../components/CreateNFT"
import { useMoralis } from "react-moralis";

const supportedChains = ["31337", "11155111", "43113"]

export default function Home() {
    const { isWeb3Enabled, chainId } = useMoralis();

    return (

        <div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {isWeb3Enabled ? (
                <div>
                    {supportedChains.includes(parseInt(chainId).toString()) ? (
                        <div >
                            <CreateNFT />
                        </div>
                    ) : (
                        <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
                    )}
                </div>
            ) : (
                <div>Please connect to a Wallet</div>
            )}
        </div>
    );
}